# Generated by Django 4.2.1 on 2023-08-30 13:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_offre', models.IntegerField(default=0)),
                ('count_demande', models.IntegerField(default=0)),
                ('supervisor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'supervisor',
            },
        ),
        migrations.CreateModel(
            name='Stagiaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_Name', models.CharField(blank=True, max_length=255, null=True)),
                ('fisrt_Name', models.CharField(blank=True, max_length=255, null=True)),
                ('school', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('motivation', models.TextField(blank=True, null=True)),
                ('niveau', models.CharField(blank=True, max_length=50, null=True)),
                ('image', models.ImageField(blank=True, default='photos/default.jpg', null=True, upload_to='photos/')),
                ('cv', models.FileField(blank=True, null=True, upload_to='pdfs/')),
                ('status', models.IntegerField(default=0)),
                ('stagiaire_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'stagiaire',
            },
        ),
        migrations.CreateModel(
            name='Offre',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('domaine', models.CharField(blank=True, max_length=255, null=True)),
                ('mission', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('skills_needed', models.CharField(blank=True, max_length=255, null=True)),
                ('dure', models.CharField(blank=True, max_length=255, null=True)),
                ('niveau_etude', models.CharField(blank=True, max_length=255, null=True)),
                ('count', models.IntegerField(default=0)),
                ('valable', models.IntegerField(default=0)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stagiaire.supervisor')),
            ],
            options={
                'db_table': 'offre',
            },
        ),
    ]
