# Generated by Django 4.2.1 on 2023-08-30 15:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stagiaire', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offre',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='stagiaire.supervisor'),
        ),
        migrations.AlterField(
            model_name='supervisor',
            name='supervisor_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
