# Generated by Django 4.2.1 on 2023-08-27 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stagiaire', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Demande',
        ),
    ]
