# Generated by Django 4.2.1 on 2023-08-30 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stagiaire', '0002_alter_offre_owner_alter_supervisor_supervisor_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offre',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stagiaire.supervisor'),
        ),
    ]
