# Generated by Django 4.2.1 on 2023-09-12 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stagiaire', '0010_alter_offre_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stagiaire',
            name='fisrt_Name',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='stagiaire',
            name='last_Name',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='stagiaire',
            name='motivation',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='stagiaire',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='stagiaire',
            name='school',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
