# Generated by Django 4.2.1 on 2023-09-12 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stagiaire', '0011_alter_stagiaire_fisrt_name_alter_stagiaire_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stagiaire',
            name='last_Name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
