# Generated by Django 4.2.1 on 2023-09-12 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stagiaire', '0012_alter_stagiaire_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stagiaire',
            name='fisrt_Name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='stagiaire',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='stagiaire',
            name='school',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
