# Generated by Django 4.2.1 on 2023-09-12 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stagiaire', '0013_alter_stagiaire_fisrt_name_alter_stagiaire_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stagiaire',
            name='image',
            field=models.ImageField(default='photos/default.jpg', upload_to='photos/'),
        ),
    ]
