# Generated by Django 4.2.1 on 2023-09-15 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stagiaire', '0016_alter_stagiaire_niveau'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stagiaire',
            name='niveau',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
