# Generated by Django 4.2.1 on 2023-09-17 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stagiaire', '0017_alter_stagiaire_niveau'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offre',
            name='count',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='offre',
            name='valable',
            field=models.IntegerField(default=1),
        ),
    ]
