# Generated by Django 4.2.1 on 2023-09-21 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stagiaire', '0019_offre_date_of_expiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='offre',
            name='demande',
            field=models.IntegerField(default=0),
        ),
    ]
