# Generated by Django 4.2.1 on 2023-09-21 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stagiaire', '0020_offre_demande'),
    ]

    operations = [
        migrations.AddField(
            model_name='offre',
            name='accepted',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='offre',
            name='confirmed',
            field=models.IntegerField(default=0),
        ),
    ]
