# Generated by Django 4.2.1 on 2023-09-21 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stagiaire', '0021_offre_accepted_offre_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='stagiaire',
            name='date_limite',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
