# Generated by Django 4.2.1 on 2023-09-22 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stagiaire', '0022_stagiaire_date_limite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stagiaire',
            name='date_limite',
        ),
    ]
