# Generated by Django 4.2.1 on 2023-09-23 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stagiaire', '0024_remove_offre_confirmed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stagiaire',
            name='offre_stage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stagiaire.offre'),
        ),
    ]
