# Generated by Django 4.2.1 on 2023-09-29 02:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stagiaire', '0025_alter_stagiaire_offre_stage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_Name', models.CharField(blank=True, default='', max_length=255)),
                ('date_of_expiry', models.DateTimeField(blank=True, null=True)),
                ('number_duc', models.IntegerField(default=0)),
                ('task_offre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stagiaire.offre')),
            ],
            options={
                'db_table': 'task',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('date_upload', models.DateTimeField(blank=True, null=True)),
                ('content', models.FileField(blank=True, null=True, upload_to='pdfs/')),
                ('owner', models.ForeignKey(limit_choices_to={'status': 2}, on_delete=django.db.models.deletion.CASCADE, to='stagiaire.stagiaire')),
                ('task_root', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stagiaire.task')),
            ],
            options={
                'db_table': 'document',
            },
        ),
    ]
