# Generated by Django 4.2.1 on 2023-09-29 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stagiaire', '0026_task_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='content',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
    ]
