# Generated by Django 4.2.1 on 2023-10-04 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stagiaire', '0027_alter_document_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fileresquest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('content', models.FileField(blank=True, null=True, upload_to='filerequest/')),
                ('status', models.IntegerField(default=0)),
                ('number_duc', models.IntegerField(default=0)),
                ('offre_files', models.ForeignKey(limit_choices_to={'owner': models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stagiaire.supervisor')}, on_delete=django.db.models.deletion.CASCADE, to='stagiaire.offre')),
                ('owner', models.ForeignKey(limit_choices_to={'status': 2}, on_delete=django.db.models.deletion.CASCADE, to='stagiaire.stagiaire')),
                ('recepteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stagiaire.supervisor')),
            ],
            options={
                'db_table': 'Fileresquest',
            },
        ),
        migrations.CreateModel(
            name='Filesrespond',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.FileField(blank=True, null=True, upload_to='files/')),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('file_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stagiaire.fileresquest')),
            ],
            options={
                'db_table': 'Filesrespond',
            },
        ),
    ]
