# Generated by Django 4.2.1 on 2023-10-04 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stagiaire', '0028_fileresquest_filesrespond'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileresquest',
            name='number_duc',
        ),
        migrations.RemoveField(
            model_name='fileresquest',
            name='offre_files',
        ),
        migrations.RemoveField(
            model_name='fileresquest',
            name='recepteur',
        ),
    ]
