# Generated by Django 4.2.1 on 2023-10-05 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stagiaire', '0029_remove_fileresquest_number_duc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileresquest',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='filesrespond',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
