# Generated by Django 4.2.1 on 2023-10-05 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stagiaire', '0030_fileresquest_description_filesrespond_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filesrespond',
            name='file_request',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stagiaire.fileresquest'),
        ),
    ]
