# Generated by Django 4.2.1 on 2023-10-08 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stagiaire', '0031_alter_filesrespond_file_request'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='number_duc',
        ),
    ]
